// GENERATED by tools/phrases/build_bank.py - do not edit.
// The built-in puzzle bank: 111 puzzles in 19 categories.
#pragma once
#include <stdint.h>

constexpr uint16_t BANK_PUZZLES = 111;
constexpr uint8_t BANK_CATS = 19;
constexpr uint8_t BANK_GROUP = 8;          // puzzles per byte-aligned group
constexpr uint8_t BANK_MAXLEN = 11;         // longest code, bits
constexpr uint32_t BANK_ID = 0xD5C16210u;
extern const uint8_t BANK_DATA[1219];       // canonical Huffman, MSB first, 0 ends a puzzle
extern const uint16_t BANK_GROUPS[17];      // byte offset of each group
extern const uint8_t BANK_START[58];       // first puzzle of (section, category); then the total
extern const uint8_t BANK_COUNTS[11];        // codes of each length, 1..BANK_MAXLEN
extern const uint8_t BANK_SYMBOLS[32];       // symbols in code order
// BANK_DATA holds the category names too, after the puzzles: name c is entry
// BANK_PUZZLES + c.
