"""Reel strips for both machines -> src/game/Strips.h.

    python tools/strips.py

A strip is laid out from symbol counts by a seeded shuffle that keeps equal
symbols apart (a reel never shows two of a kind touching), except the Fortune
machine's coins, which sit in one stack per reel: that is what makes six on
screen (Hold and Spin) possible at all. The returns these strips give are
checked by tools/tests/test_slots.cpp; change the counts here, not the header.
"""
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "game" / "Strips.h"

# Classic, 35 stops a reel, in the order of the sprite sheet:
# CHERRY LEMON BELL BAR SEVEN CHEST PLUM GRAPE WATERMELON BANANA CLOVER
# HORSESHOE DIAMOND APPLE ORANGE
CLASSIC = [[4, 4, 2, 2, 2, 1, 3, 2, 2, 3, 2, 1, 1, 3, 3]] * 3
# Fortune: JADE FAN LANTERN ENVELOPE KOI INGOT LION DRAGON GONG, then the
# coin stack's height. The dragon only lives on reels 2-4.
FORTUNE = [
    #  J  F  L  E  K  I  Li D  G   coins
    ([6, 5, 5, 5, 3, 2, 2, 0, 2], 3),
    ([6, 6, 5, 4, 3, 3, 2, 1, 1], 2),
    ([5, 6, 6, 4, 3, 2, 2, 1, 1], 3),
    ([6, 5, 5, 5, 3, 3, 2, 1, 1], 2),
    ([6, 5, 5, 4, 3, 3, 2, 0, 2], 3),
]
COIN = 9
# Sweet, 24 stops a reel: GUMDROP CANDY CHOCOLATE DONUT CUPCAKE ICECREAM BEAR LOLLY
SWEET = [
    [5, 5, 4, 3, 3, 2, 1, 1],
    [5, 5, 4, 3, 3, 2, 1, 1],
    [5, 5, 4, 3, 3, 2, 1, 1],
]
SWEET_SEED = 1
FORTUNE_SEED = 3


def spread(counts, rng):
    """Shuffle so no symbol is next to itself (wrapping), and if the counts
    allow it, not within two stops either."""
    syms = [s for s, n in enumerate(counts) for _ in range(n)]
    n = len(syms)
    for gap in (2, 1):
        for _ in range(20000):
            rng.shuffle(syms)
            if all(syms[i] != syms[(i + k) % n] for i in range(n) for k in range(1, gap + 1)):
                return syms[:]
    raise SystemExit(f"cannot spread {counts}")


def main():
    rng = random.Random(777)
    out = ["// GENERATED by tools/strips.py - do not edit.", "#pragma once", "#include <stdint.h>", ""]
    strips = [spread(c, rng) for c in CLASSIC]
    n = len(strips[0])
    assert all(len(s) == n for s in strips)
    out.append(f"constexpr uint8_t CLASSIC_STOPS = {n};")
    out.append(f"static const uint8_t CLASSIC_STRIP[3][{n}] = {{")
    out += ["    {" + ",".join(map(str, s)) + "}," for s in strips]
    out.append("};")
    rng = random.Random(FORTUNE_SEED)       # its own sequence: changing LUCKY 7 leaves these alone
    strips = []
    for counts, coins in FORTUNE:
        s = spread(counts, rng)
        at = rng.randrange(len(s))
        strips.append(s[:at] + [COIN] * coins + s[at:])
    n = len(strips[0])
    assert all(len(s) == n for s in strips), [len(s) for s in strips]
    out.append(f"constexpr uint8_t FORTUNE_STOPS = {n};")
    out.append(f"static const uint8_t FORTUNE_STRIP[5][{n}] = {{")
    out += ["    {" + ",".join(map(str, s)) + "}," for s in strips]
    out.append("};")
    rng = random.Random(SWEET_SEED)
    strips = [spread(c, rng) for c in SWEET]
    n = len(strips[0])
    assert all(len(s) == n for s in strips)
    out.append(f"constexpr uint8_t SWEET_STOPS = {n};")
    out.append(f"static const uint8_t SWEET_STRIP[3][{n}] = {{")
    out += ["    {" + ",".join(map(str, s)) + "}," for s in strips]
    out.append("};")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
