// GENERATED by tools/assets.py - do not edit.
// Suit glyphs by Press Play On Tape (Apache-2.0), via CHBlackjack; card
// ranks, pips and court portraits from CHBlackjack; the glove from
// CHChess. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t SUIT_SMALL[20];
extern const uint8_t RANK_GLYPH[91];
extern const uint8_t RANK_WIDTH[13];
extern const uint8_t PIP9[132];
extern const uint16_t PIP9_AT[4];
extern const uint8_t PIP13[178];
extern const uint16_t PIP13_AT[4];
extern const uint8_t COURT_JACK[98];
extern const uint8_t COURT_QUEEN[112];
extern const uint8_t COURT_KING[110];
extern const uint8_t LOGO[112];
constexpr int LOGO_W = 59;
constexpr int LOGO_H = 14;
extern const uint8_t HAND[111];
constexpr int HAND_TIP = 5;
