// Where the puzzles come from.
//
// The game always has the built-in bank (src/bank/BankData.*, generated by
// tools/phrases/build_bank.py: Huffman-coded text in flash). With a card
// holding PHRASES.BNK in the slot it draws from that instead (SdBank.cpp).
//
// A puzzle is addressed by its section (round, toss-up, bonus: Show.h's
// SEC_*) and an index below count(section). The Deck deals them without
// repeats: each section is walked in a shuffled order that a seed fixes, so
// only the seed and three cursors need saving.
//
// fetch() may touch the SD card, which shares the LCD's SPI: call it only
// after gfx_wait().
#pragma once
#include <stdint.h>

namespace bank {

constexpr uint8_t SECTIONS = 3;
constexpr uint8_t TEXT_MAX = 56, CAT_MAX = 20;      // buffer sizes, NUL included

void     begin();                   // look for a card with a bank on it; call after gfx_wait()
bool     card();
uint16_t count(uint8_t section);
uint32_t id();                      // changes when the bank does (a new card, a new build)
// text: lines split by '\n' (Puzzle::set). False: the card stopped answering.
bool     fetch(uint8_t section, uint16_t index, char *text, char *category);

// The built-in bank, whatever card() says.
uint16_t flashCount(uint8_t section);
void     flashFetch(uint8_t section, uint16_t index, char *text, char *category);

// A bijection on 0..n-1 chosen by key: position i of a shuffled order.
uint16_t permute(uint16_t i, uint16_t n, uint32_t key);

struct Deck {
    uint32_t seed;
    uint32_t bankId;                // the bank the cursors belong to
    uint16_t cursor[SECTIONS];

    void     shuffle(uint32_t s);   // a fresh order from the top
    // The next puzzle of a section: reshuffles when the bank changed, starts
    // a new pass (in a new order) when a section runs out.
    uint16_t draw(uint8_t section);
};

}  // namespace bank
