// CHYacht - YACHT DICE for the RPGame handheld (CH32X035, 128x128 ST7735,
// piezo): five dice, three rolls, thirteen boxes, in the style of
// CHBlackjack and CHCraps - the same felt, the same lettering, and CHCraps's
// 3D dice thrown five at a time down a wooden tray.
//
// The dealer's art and the 3x5 font come from Press Play On Tape's Arduboy
// Blackjack (Apache-2.0) by Simon Holmes (filmote) and Stephane C
// (vampirics), by way of CHBlackjack; see NOTICE.
//
// The files:
//   Screens.*          title, play (pause menu), options, stats, the endings
//   Yacht.*            the rules, the money and the house player (no graphics)
//   Presenter.*        the play screen's show: dice into the tray, scores, coins
//   Cam.*, Dice3D.*    the dice cam: five 3D dice thrown down the tray
//   Bar.*, Chips.*, Wall.*, Layout.h   the bar, chips and dice faces, the wall
//                      and the dealer; where everything goes
//   Fx.*, Sounds.*     particles, banners, floating texts; the sound effects
//   Save.*             what a save holds
//   src/assets/        the art, generated by tools/assets.py
//
// Frame loop: logic runs while the previous frame is still going out over
// DMA; drawing waits for it (one framebuffer), then the new frame is sent.
#include <RPGame.h>
#include "config.h"
#include "Screens.h"

void setup() {
    rpgame.boot();
    dbg::begin("CHYD " CHYD_VERSION);     // the debug protocol's hello (CHGAME_DEBUG builds)
    gfx_begin(GFX_DIV2, GFX_12BPP);
    pal::init();
    screens::begin();
    rpgame.setFrameRate(CHYD_FPS);
#if CHGAME_DEBUG
    dbg::hook = screens::debugCommand;
#endif
}

void loop() {
    dbg::poll();
    if (!rpgame.nextFrame()) return;
    dbg::markUpdateStart();
    // Logic runs at a fixed 60 Hz. If a heavy frame made drawing fall
    // behind, catch up (up to three ticks) before drawing again, so the dice
    // never slow down.
    uint8_t ticks = 0;
    do {
        rpgame.pollButtons();
        pal::tick();
        screens::update();
    } while (++ticks < 3 && rpgame.nextFrame());
    pal::commit();                  // staged by RPGfx: lands with the next flush
    gfx_wait();
    dbg::markRenderStart();
    screens::render(rpgame.frameCount);
    dbg::markRenderEnd();
    gfx_flushAsync();
}
