// GENERATED by tools/assets.py - do not edit.
// Art derived from Press-Play-On-Tape/Blackjack (Apache-2.0) by filmote &
// vampirics, recoloured 2026 for RPGame by bateske; plus new art drawn for
// this port (tools/art/). See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t SUIT_SMALL[20];
extern const uint8_t RANK_GLYPH[91];
extern const uint8_t RANK_WIDTH[13];
extern const uint8_t PIP9[132];
extern const uint16_t PIP9_AT[4];
extern const uint8_t PIP13[178];
extern const uint16_t PIP13_AT[4];
extern const uint8_t COURT_JACK[98];
extern const uint8_t COURT_QUEEN[112];
extern const uint8_t COURT_KING[110];
extern const uint8_t DEALER[487];
extern const uint8_t DEALER_ALT_REMAP[16];
extern const uint8_t FACE_NORMAL[119];
extern const uint8_t LOGO[182];
extern const uint8_t YOUWON1[240];
constexpr int YOUWON1_W = 119;
extern const uint8_t YOUWON2[224];
constexpr int YOUWON2_W = 107;
extern const uint8_t BROKE1[192];
constexpr int BROKE1_W = 91;
extern const uint8_t BROKE2[160];
constexpr int BROKE2_W = 73;
extern const uint8_t PPOT_LOGO[288];
constexpr int PPOT_LOGO_W = 65;
constexpr int PPOT_LOGO_H = 32;
extern const uint16_t FACE_EDITS[138];
extern const uint16_t FACE_EDIT_AT[7];
