// Generated by tools/wheel.py - do not edit.
// The roulette rotor's polar angle map (docs/design/wheel.md section 2.1):
// one quadrant around the pixel centre (cx, cy), rows j = 0..22 below it.
// Mirroring: right half i >= 0, left half i >= 1; rows below j >= 0, above j >= 1.
// Full-turn step s from q: right-down q, left-down 127-q, left-up 128+q,
// right-up 255-q (256 steps per turn, floor-based, clockwise from +x).
#pragma once
#include <stdint.h>

constexpr int WHEEL_ROWS = 23, WHEEL_R_IN = 26, WHEEL_R_OUT = 44;
constexpr int WHEEL_BINS = 256;              // angle steps per turn
constexpr int WHEEL_MAP_SIZE = 515;
extern const uint8_t WHEEL_SPAN[WHEEL_ROWS][2];   // row j: pixels dx = i for i in [a, b); a = 0 once j > 13
extern const uint8_t WHEEL_MAP[WHEEL_MAP_SIZE];   // rows packed together, 1 byte per pixel: band<<6 | q: band 0 floor, 1 number ring, 2 mark, 3 GOLD; q 0..63

// Wheel orders: wheel index -> number, clockwise from the zero. 37 means 00.
constexpr uint8_t WHEEL_00 = 37;
extern const uint8_t EU_ORDER[37];
extern const uint8_t US_ORDER[38];
