"""Check the puzzle sources and pack them.

    python tools/puzzles/build_pack.py                 the built-in puzzles (tools/puzzles/src/*.txt)
                                                       -> src/game/PuzzleData.{h,cpp}
    python tools/puzzles/build_pack.py --cwd OUT.CWD --name NAME FILE.txt ...
                                                       a pack for the SD card (folder CHCW)
    python tools/puzzles/build_pack.py --check         only check: the sources are sound and
                                                       PuzzleData.cpp is what they build
    python tools/puzzles/build_pack.py --refit         work the Huffman code out again from the
                                                       sources (huff.json): only before any pack
                                                       has been handed out, since it changes the
                                                       format

Every puzzle is checked (tools/puzzles/cwformat.py check) and its blob is
decoded again with the reference decoder before anything is written.
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))
import cwformat as cw  # noqa: E402

SRC = HERE / "src"
OUT_H = ROOT / "src" / "game" / "PuzzleData.h"
OUT_C = ROOT / "src" / "game" / "PuzzleData.cpp"
BUILTIN_MAX = 20                    # what the save page keeps records for
LEAN_COUNT = 3                      # CHCW_LEAN builds (device debug) carry only the first few


def load(paths, strict=True):
    puzzles, bad = [], False
    for path in paths:
        p = cw.parse(path)
        problems = cw.check(p, strict)
        for msg in problems:
            print(f"{Path(path).name}: {msg}")
        bad |= bool(problems)
        puzzles.append(p)
    if bad:
        raise SystemExit("fix the puzzles above")
    return puzzles


def texts(p):
    g = p["grid"]
    across, down = cw.numbering(g)
    return [p["title"]] + [p["across"][w[0]] for w in across] + [p["down"][w[0]] for w in down]


def refit(puzzles):
    freq = [0] * cw.NSYM
    for p in puzzles:
        for t in texts(p):
            for ch in t:
                freq[cw.ALPHA.index(ch)] += 1
            freq[cw.END] += 1
    lens = cw.huff_lengths(freq)
    (HERE / "huff.json").write_text(json.dumps({"alphabet": cw.ALPHA + "<END>", "lengths": lens}) + "\n")
    print("huff.json rewritten")


def blobs_of(puzzles):
    out = []
    for p in puzzles:
        b = cw.encode(p)
        q = cw.decode(b)
        if any(q[k] != p[k] for k in ("title", "difficulty", "grid", "across", "down")):
            raise SystemExit(f"{p['name']}: does not decode to itself")
        out.append(b)
    return out


def c_array(name, data, per_line=24):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        lines.append("    " + ", ".join(str(v) for v in data[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="*")
    ap.add_argument("--cwd")
    ap.add_argument("--name", default="PUZZLES")
    ap.add_argument("--refit", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--loose", action="store_true", help="skip the built-in puzzles' style rules")
    a = ap.parse_args()
    if a.cwd:
        puzzles = load(a.files, not a.loose)
        pack = cw.make_pack(a.name, blobs_of(puzzles))
        Path(a.cwd).write_bytes(pack)
        print(f"{a.cwd}: {len(puzzles)} puzzles, {len(pack)} bytes")
        return
    puzzles = load(sorted(SRC.glob("*.txt")))
    if len(puzzles) > BUILTIN_MAX:
        raise SystemExit(f"more than {BUILTIN_MAX} built-in puzzles")
    if a.refit or not (HERE / "huff.json").exists():
        refit(puzzles)
    blobs = blobs_of(puzzles)
    pack = cw.make_pack("BUILT-IN", blobs)
    lean = cw.make_pack("BUILT-IN", blobs[:LEAN_COUNT])
    if a.check:
        text = OUT_C.read_text()
        text = text[text.index("#else"):]
        body = text[text.index("BUILTIN["):]
        have = bytes(int(v) for v in body[body.index("{") + 1:body.index("}")].replace("\n", " ").split(",") if v.strip())
        if have != pack:
            raise SystemExit("src/game/PuzzleData.cpp is stale: run tools/puzzles/build_pack.py")
        print(f"{len(puzzles)} puzzles sound, PuzzleData.cpp up to date ({len(pack)} bytes)")
        return
    _, counts, order = cw.canonical(cw.load_lengths())
    syms = [0 if s == cw.END else ord(cw.ALPHA[s]) for s in order]
    OUT_H.write_text(
        "// Generated by tools/puzzles/build_pack.py - do not edit.\n#pragma once\n#include <stdint.h>\n"
        "#include \"../../config.h\"\n\n"
        f"constexpr uint8_t HUFF_MAX = {cw.MAX_CODE};                // the longest code\n"
        f"extern const uint8_t HUFF_COUNT[{cw.MAX_CODE}];           // codes of each length 1..HUFF_MAX\n"
        f"extern const char HUFF_SYM[{cw.NSYM}];              // the characters in code order (0 = end of text)\n"
        "#if CHCW_LEAN\n"
        f"extern const uint8_t BUILTIN[{len(lean)}];         // the built-in pack, cut to its first {LEAN_COUNT} puzzles\n"
        "#else\n"
        f"extern const uint8_t BUILTIN[{len(pack)}];        // the built-in pack ({len(puzzles)} puzzles)\n"
        "#endif\n",
        newline="\n")
    OUT_C.write_text(
        "// Generated by tools/puzzles/build_pack.py - do not edit.\n"
        "// The puzzles are in tools/puzzles/src/.\n#include \"PuzzleData.h\"\n\n"
        + c_array("HUFF_COUNT", counts) + "\n\n"
        + f"const char HUFF_SYM[{cw.NSYM}] = {{" + ", ".join(str(v) for v in syms) + "};\n\n"
        + "#if CHCW_LEAN\n" + c_array("BUILTIN", list(lean)) + "\n#else\n"
        + c_array("BUILTIN", list(pack)) + "\n#endif\n", newline="\n")
    chars = sum(len(t) + 1 for p in puzzles for t in texts(p))
    bits = sum(8 * len(b) for b in blobs)
    print(f"{len(puzzles)} puzzles, pack {len(pack)} bytes "
          f"({', '.join(str(len(b)) for b in blobs)}); {chars} characters of text")


if __name__ == "__main__":
    main()
