// GENERATED by tools/assets.py - do not edit.
// Suit glyphs by Press Play On Tape (Apache-2.0), via CHBlackjack; card
// ranks, pips and court portraits from CHBlackjack; the glove from
// CHChess. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t SUIT_SMALL[20];
extern const uint8_t RANK_GLYPH[91];
extern const uint8_t RANK_WIDTH[13];
extern const uint8_t PIP9[132];
extern const uint16_t PIP9_AT[4];
extern const uint8_t BUST_JACK[67];
extern const uint8_t BUST_QUEEN[71];
extern const uint8_t BUST_KING[67];
extern const uint8_t BACK_ROBOT[130];
extern const uint8_t BACK_ROSES[154];
extern const uint8_t BACK_CASTLE[124];
extern const uint8_t BACK_ISLAND[108];
extern const uint8_t BACK_FISH[123];
extern const uint8_t BACK_SHELL[180];
extern const uint8_t BACK_CHERRY[120];
extern const uint8_t BACK_DICE[94];
extern const uint8_t BACK_LUCKY[94];
extern const uint8_t BACK_CHIP[98];
extern const uint8_t LOGO[266];
constexpr int LOGO_W = 112;
constexpr int LOGO_H = 19;
extern const uint8_t HAND[111];
constexpr int HAND_TIP = 5;
