// Scores generated by tools/make_music.py (song order matches enum Song).
#pragma once
#include <stddef.h>
#include <stdint.h>

namespace music {
void get(uint8_t song, bool loop, const uint8_t *&data, size_t &n);
}
