// Generated by tools/layouts.py from tools/layouts/*.txt - do not edit.
#pragma once
#include <stdint.h>

namespace board {

// Per layout: runs of (layer, y2, x2, tiles two apart), ended by 0xFF.
extern const uint8_t *const LAYOUT[4];
extern const char *const LAYOUT_NAME[4];
extern const uint8_t LAYOUT_TILES[4];

}  // namespace board
