// Generated by tools/assets.py - do not edit.
#pragma once
#include <stdint.h>

extern const uint8_t HAND[111];                            // span4, fingertip on the bottom row
constexpr uint8_t HAND_TIP = 5;                           // its column
extern const uint8_t HAND_SIDE[89];                       // the glove pointing right, 16 x 13
extern const uint8_t FONT[718];                         // the display font (tools/art/font.txt): per glyph its
                                                            // character, width, top << 4 | rows, the rows' bits; 0 ends
extern const uint16_t TILEFONT[498];                     // the close-up's letters (tools/art/tilefont.txt), A to Z:
                                                            // width | rows << 8, the rows of ink, the rows of half ink
