"""Compose CHBlackjack's music into Playtune bytes for CHGameSound.

    python tools/make_music.py      -> src/audio/Music.cpp

The songs below are "NOTE:len" tokens per voice (the repository's
tools/music/composer.py has the format and turns them into Playtune bytes). All tunes here are original.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "src" / "audio" / "Music.cpp"
sys.path.insert(0, str((next(p for p in Path(__file__).resolve().parents if (p / "libraries" / "RPGame").is_dir()) / "tools")))     # the repository's tools/: music.composer
from music.composer import write_music_cpp  # noqa: E402

SONGS = {
    # Title: a ragtime-flavoured shuffle, eight bars, loops.
    "TITLE": dict(eighth_ms=190, voices=[
        "C6 E6 G6 A6 G6 E6 C6 D6  E6:2 D6 C6 A5:2 G5:2 "
        "F6 A6 C7 D7 C7 A6 F6 G6  A6:2 G6 F6 D6:2 C6:2 "
        "C6 E6 G6 A6 Bb6 A6 G6 E6  F6:2 A6:2 G6:2 E6:2 "
        "D6 F6 A6 G6 F6 E6 D6 B5  C6:4 R:4",
        # Accompaniment: detached eighths an octave up, where the piezo is
        # as loud as the melody (at C5 it is far quieter, and taking turns
        # with a much quieter note is what made the arpeggio sound garbled).
        "C6 R G6 R C6 R G6 R  C6 R G6 R C6 R G6 R "
        "F6 R C7 R F6 R C7 R  F6 R C7 R F6 R C7 R "
        "C6 R G6 R C6 R E6 R  F6 R C7 R A6 R C7 R "
        "G6 R D7 R G6 R B6 R  C7 R G6 R C6 R:3",
    ]),
    # Won the game: fanfare, plays once.
    "VICTORY": dict(eighth_ms=110, voices=[
        "G6 G6 G6 C7:3 R G6 C7 E7:3 R C7 E7 G7:6 R:2 "
        "E7 F7 G7 A7 G7 E7 C7 E7 G7:8",
        "C6:3 R C6:3 R E6:3 R G6:6 R:2 C6:4 E6:4 C6:8",
    ]),
    # Broke: a slow minor blues, loops.
    "BROKE": dict(eighth_ms=260, voices=[
        "A6:2 G6:2 E6:2 D6:2 C6:4 A5:4  D6:2 C6:2 A5:2 G5:2 A5:8 "
        "E6:2 D6:2 C6:2 B5:2 A5:3 G#5 A5:4  R:8",
        "A6:4 E6:4 A6:4 E6:4  D6:4 A6:4 D6:4 A6:4 E6:4 B6:4 A6:8 R:8",
    ]),
}

LOOPS = {"TITLE": True, "VICTORY": False, "BROKE": True}
HEADER = "// GENERATED by tools/make_music.py - do not edit. Original tunes."
DEBUG_NOTE = "// Debug builds (the test protocol: rpgame build --debug) leave the scores"


if __name__ == "__main__":
    write_music_cpp(OUT, SONGS, LOOPS, HEADER, DEBUG_NOTE, ROOT)
