// Generated by tools/assets.py - do not edit.
#pragma once
#include <stdint.h>

extern const uint8_t CHIP[];                                 // span4: a man, from the table's edge
constexpr int8_t CHIP_AX = 6, CHIP_AY = 6;                    // its base centre
extern const uint8_t CHIP_TOP[];                             // span4: from above
extern const uint8_t SIDE_REMAP[2][16];                      // art colour -> White's, Black's (tools/art/sides.txt)
extern const uint8_t KING_REMAP[2][16];                      // ... with the crown showing
extern const uint8_t HAND[];                                 // span4, fingertip on the bottom row
constexpr uint8_t HAND_TIP = 5;                           // its column
