"""The host tests' helpers (tools/game.py uses them): the built-in puzzles
decoded by the Python reference decoder (tools/puzzles/cwformat.py) into
build/expect.h, which the C++ tests hold the game's own decoder to; the
card tests, which read packs out of FAT16 and FAT32 images made here
(--quick: FAT16 only; a FAT32 image is 34 MB); and the card the card_*
scripts play with.
"""
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE.parent / "puzzles"))
import cwformat as cw  # noqa: E402


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def builtin_pack():
    """The BUILTIN array out of the generated PuzzleData.cpp."""
    text = (ROOT / "src" / "game" / "PuzzleData.cpp").read_text()
    text = text[text.index("#else"):]               # (past the cut-down pack of CHCW_LEAN builds)
    body = text[text.index("BUILTIN["):]
    body = body[body.index("{") + 1:body.index("}")]
    return bytes(int(v) for v in body.replace("\n", " ").split(",") if v.strip())


def write_expect(path):
    _, blobs = cw.read_pack(builtin_pack())
    out = ["// Generated by tools/tests/cwtests.py from the reference decoder.", "static const std::vector<XPuzzle> EXPECT = {"]
    for blob in blobs:
        p = cw.decode(blob)
        n = len(p["grid"])
        across, down = cw.numbering(p["grid"])
        words = [(num, r * n + c, ln, 0, p["across"][num]) for num, r, c, ln in across]
        words += [(num, r * n + c, ln, 1, p["down"][num]) for num, r, c, ln in down]
        out.append(f"  {{{c_str(p['title'])}, {n}, {p['difficulty']}, {c_str(''.join(p['grid']))}, {{")
        out += [f"    {{{num}, {start}, {ln}, {d}, {c_str(clue)}}}," for num, start, ln, d, clue in words]
        out.append("  }},")
    out.append("};")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


def card_tests(exe, quick):
    """Cards of each kind, with packs made from the built-in puzzles."""
    import mkcard
    import fatimg
    build = HERE / "build"
    _, blobs = cw.read_pack(builtin_pack())
    packs = {
        "ALPHA.CWD": cw.make_pack("ALPHA", blobs[:1]),
        "BETA.CWD": cw.make_pack("BETA PACK", list(reversed(blobs))),
        "GAMMA.CWD": cw.make_pack("GAMMA", (blobs * 32)[:32]),
    }
    expect = build / "card_expect.txt"
    with open(expect, "w") as f:
        for data in packs.values():
            name, bl = cw.read_pack(data)
            titles = "|".join(cw.decode(b)["title"] for b in bl)
            f.write(f"{name.replace(' ', '_')} {int.from_bytes(data[20:24], 'little')} {len(bl)} {titles}\n")
    # Files that are not packs: the game must pass over them.
    junk = dict(packs)
    junk["NOTES.TXT"] = b"hello"
    junk["EMPTY.CWD"] = b""
    junk["SHORT.CWD"] = packs["BETA.CWD"][:20]
    junk["CUT.CWD"] = packs["GAMMA.CWD"][:3000]
    junk["NOISE.CWD"] = bytes((i * 37 + 11) & 255 for i in range(5000))
    bad = bytearray(packs["BETA.CWD"])
    bad[30] ^= 0x40
    junk["BADCRC.CWD"] = bytes(bad)
    ok = True

    def run(*args):
        nonlocal ok
        r = subprocess.run([str(exe), *map(str, args)], capture_output=True, text=True)
        print("  " + (r.stdout.strip().splitlines() or ["(no output)"])[-1])
        if r.returncode:
            print(r.stdout[-1500:] + r.stderr[-1500:])
            ok = False

    print("card: none")
    run("--none")
    cases = [("fat16", dict(fs="fat16")),
             ("fat16, long names, decoys, files in pieces", dict(fs="fat16", lfn=True, decoys=True, fragment=3, seed=7)),
             ("fat16, no partition table", dict(fs="fat16", mbr=False))]
    if not quick:
        cases += [("fat32", dict(fs="fat32")),
                  ("fat32, long names, decoys, files in pieces",
                   dict(fs="fat32", lfn=True, decoys=True, fragment=4, seed=3))]
    img = build / "card.img"
    for label, kw in cases:
        print(f"card: {label}")
        mkcard.make(img, junk, **kw)
        run(img, expect)
    # Cards with nothing for the game: the states it reports
    # (pack::Card: 1 unreadable, 2 exFAT, 3 no packs).
    print("card: no CHCW folder / no packs in it / exFAT / blank")
    fatimg.build_image(str(img), {"OTHER/ALPHA.CWD": packs["ALPHA.CWD"], "ALPHA.CWD": packs["ALPHA.CWD"]}, fs="fat16")
    run(img, expect, 3)
    mkcard.make(img, {"NOISE.CWD": junk["NOISE.CWD"], "X.TXT": b"x"}, fs="fat16")
    run(img, expect, 3)
    fatimg.make_exfat_stub(str(img))
    run(img, expect, 2)
    img.write_bytes(bytes(512 * 64))
    run(img, expect, 1)
    img.unlink()
    return ok


def make_card(ctx=None):
    """The card the card_* scripts play with: two packs made of built-in puzzles."""
    import mkcard
    _, blobs = cw.read_pack(builtin_pack())
    out = ROOT / "out"
    out.mkdir(exist_ok=True)
    mkcard.make(out / "card.img", {"BONUS.CWD": cw.make_pack("BONUS", blobs[2:5]),
                                   "EXTRA.CWD": cw.make_pack("EXTRA", blobs[:1])}, fs="fat16")
    return out / "card.img"
