// CHBingo - 75-ball bingo for the RPGame handheld (CH32X035, 128x128 ST7735,
// piezo), in the casino style of CHBlackjack and its siblings: the dealer
// from CHBlackjack's tables calls the balls, and the player races a hall of
// rivals across up to nine cards, only one and a half of them in view.
//
// Frame loop: logic runs while the previous frame is still going out over
// DMA; drawing waits for it (one framebuffer), then the new frame is sent.
//
// The files, by role:
//   rules     Bingo.*: the cards, the draw, the hall, the money (no graphics)
//   screens   Screens.*: title, play, pause, options, stats, broke
//   show      Presenter.*: the rules' events turned into motion and sound
//   drawing   Table.* (the wall and the caller), Cards.* (cards, buy-in, bar),
//             Layout.h (every coordinate), Fx.* (particles, banners)
//   sound     Sounds.*        saving  Save.*        switches  config.h
//   art       src/assets/ (generated by tools/assets.py; not edited by hand)
#include <RPGame.h>
#include "config.h"
#include "Screens.h"
#include "Save.h"

#if CHGAME_DEBUG
// Game commands for the debug protocol (tools/chsim/chdrive.py 'say').
//   R <seed>          reseed the rules' generator
//   J <T|P|O|S|L>     jump to a screen (P: a new game at the buy-in)
//   C <n>             buy n cards and start the round
//   F <n[,n...]>      the next balls called
//   G <card>          put that card in play (0-based)
//   D                 daub every waiting number on every card
//   W                 daub the middle row of the card in play: a bingo
//   I <0|1|2>         the win banner: by chance, always "IT'S A BINGO!", never
//   H <call>          the call a rival completes a line on
//   X <1|2|3>         hand over a power-up (wild, freeze, 2x)
//   M <amount>        set the purse;  A <amount>  set the jackpot
//   Y                 print the game state (the save test)
//   V                 power off and on: reload from the save pages
//   E <1|0>           let a debug build on the board write its save pages
static bool debugHook(char cmd, const char *args) {
    switch (cmd) {
        case 'R': screens::debugSeed(dbg::parseNum(args, 10)); return true;
        case 'J': screens::debugJump(args[0]); return true;
        case 'F': {
            const char *p = args;
            while (*p) {
                if (!screens::debugGame('F', dbg::parseNum(p, 10))) return false;
                while (*p == ' ' || *p == ',') p++;
                if (*p && (*p < '0' || *p > '9')) break;
            }
            return true;
        }
        case 'Y': {
            char buf[96];
            screens::debugState(buf);
            dbg::print(buf);
            return true;
        }
        case 'E': save::allowWrites(args[0] == '1'); return true;
        default: return screens::debugGame(cmd, dbg::parseNum(args, 10));
    }
}
#endif

void setup() {
    rpgame.boot();
    dbg::begin("CHBN " CHBN_VERSION);     // the debug protocol's hello (CHGAME_DEBUG builds)
    gfx_begin(GFX_DIV2, GFX_12BPP);
    pal::init();
    screens::begin();
    rpgame.setFrameRate(CHBN_FPS);
#if CHGAME_DEBUG
    dbg::hook = debugHook;
#endif
}

void loop() {
    dbg::poll();
    if (!rpgame.nextFrame()) return;
    dbg::markUpdateStart();
    // Logic runs at a fixed 60 Hz. If a heavy frame made drawing fall
    // behind, catch up (up to three ticks) before drawing again, so the
    // caller's clock never slows down.
    uint8_t ticks = 0;
    do {
        rpgame.pollButtons();
        pal::tick();
        screens::update();
    } while (++ticks < 3 && rpgame.nextFrame());
    pal::commit();                  // staged by RPGfx: lands with the next flush
    gfx_wait();
    dbg::markRenderStart();
    screens::render(rpgame.frameCount);
    dbg::markRenderEnd();
    gfx_flushAsync();
}
