// Generated by tools/assets.py - do not edit.
// The dealer is Press Play On Tape's (Apache-2.0), as recoloured for
// CHBlackjack; the glove is CHChess's. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[487];                          // the dealer, span4, 48 x 42
extern const uint8_t FACE_NORMAL[119];                     // his face, a 24 x 18 patch at (12, 14)
extern const uint16_t FACE_EDITS[138];                    // the other expressions, as the pixels that differ:
extern const uint16_t FACE_EDIT_AT[7];                     // (y * 24 + x) << 4 | colour; each one's start, and the end
extern const uint8_t DISC[59];                            // span4, 10 x 10, neutral tones
extern const uint8_t DISC_REMAP[2][16];                     // ... as RED's, as GOLD's (tools/art/sides.txt)
extern const uint8_t DISC_BIG[145];                       // the same disc, 20 x 20: the close-ups
extern const uint8_t CELL_FRAME[46];                      // a square of the board with its hole: over a falling disc
extern const uint8_t HAND[111];                            // span4, fingertip on the bottom row
constexpr uint8_t HAND_TIP = 5;                           // its column
extern const uint8_t FONT[718];                         // the display font (tools/art/font.txt): per glyph its
                                                            // character, width, top << 4 | rows, the rows' bits; 0 ends
