"""Compose CHWordWheel's music into Playtune bytes for CHGameSound.

    python tools/make_music.py      -> src/audio/Music.cpp

The songs below are "NOTE:len" tokens per voice (the repository's
tools/music/composer.py has the format and turns them into Playtune bytes). The tune is original.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "src" / "audio" / "Music.cpp"
sys.path.insert(0, str((next(p for p in Path(__file__).resolve().parents if (p / "libraries" / "RPGame").is_dir()) / "tools")))     # the repository's tools/: music.composer
from music.composer import write_music_cpp  # noqa: E402

SONGS = {
    # Title: a game-show theme in 4/4 (eight eighths a bar), eight bars, loops.
    # The tune climbs a chord like a wheel coming round, answers itself a
    # step down, and ends on a pick-up back to the top; under it, a walking
    # two-note vamp as detached eighths, where the piezo is as loud as the
    # melody.
    "TITLE": dict(eighth_ms=120, voices=[
        "G5 C6 E6 G6:2 E6 G6:2  A6:2 G6 E6 C6:2 R:2  F5 A5 C6 F6:2 C6 F6:2  G6:2 F6 D6 B5:2 R:2 "
        "G5 C6 E6 G6:2 E6 C7:2  B6:2 A6 G6 E6:2 R:2  F6 E6 D6 C6 D6:2 G5:2  C6:3 R G6 G6 C7:2",
        "C6 R G6 R C6 R G6 R  C6 R E6 R A5 R E6 R  F5 R C6 R F5 R C6 R  G5 R D6 R G5 R B5 R "
        "C6 R G6 R C6 R G6 R  E6 R B5 R A5 R E6 R  F5 R A5 R G5 R B5 R  C6 R G5 R C6:2 R:2",
    ]),
}

LOOPS = {"TITLE": True}
HEADER = "// GENERATED by tools/make_music.py - do not edit. An original tune."
DEBUG_NOTE = "// Debug builds (the test protocol: rpgame build --debug, and the simulator) leave the scores"


if __name__ == "__main__":
    write_music_cpp(OUT, SONGS, LOOPS, HEADER, DEBUG_NOTE, ROOT)
