// The CPU's judgement: a small neural network that looks at a position
// just after a side has moved and says how likely that side is to win.
//
// Nobody wrote its knowledge down. It learned by playing itself a few hundred
// thousand games on a PC (tools/train: temporal-difference learning, as
// TD-Gammon did in 1992), and what it learned is the table of small
// integers in src/ai/NetData.cpp, generated by that tool. Here is only the
// arithmetic to use it: integers throughout (this chip has no FPU, and
// soft-float would cost 8 KB), and the same code runs in the trainer, so
// what was measured there is what plays here.
//
// The position is fed in as rows of the first table, added up: every checker
// owns one row. For each side (the one that just moved, then the one about
// to roll) and each of its points: a row for a first checker there, one for
// a second, one for a third, and one added again for each checker past
// three; then a row per checker on the bar and a row per checker borne off.
#pragma once
#include <stdint.h>
#include "Rules.h"

#ifndef NET_H
#define NET_H 16            // hidden units (the trainer builds other sizes with -DNET_H=n)
#endif

namespace net {

constexpr int H = NET_H;
constexpr int SIDE_ROWS = 24 * 4 + 2, ROWS = 2 * SIDE_ROWS;
#ifndef NET_W1_SCALE
#define NET_W1_SCALE 32
#endif
constexpr int W1_SCALE = NET_W1_SCALE;  // first table: weight * 32, sums in the same units
constexpr int W2_SCALE = 16;            // second: weight * 16, against activations of 0..255

// The tables. The trainer fills them in as it goes (NET_HOST); on the device
// they are constants in flash.
#ifdef NET_HOST
#define NET_CONST
#else
#define NET_CONST const
#endif
extern NET_CONST int8_t HID_W[ROWS][H];
extern NET_CONST int16_t HID_B[H];
extern NET_CONST int8_t OUT_W[H];
extern NET_CONST int32_t OUT_B;

// f(row, times) for every row a position adds. The one place the encoding
// is written down: the trainer's floating-point network uses it too.
template <class F> inline void forEachRow(const bg::Board &b, uint8_t mover, F f) {
    for (uint8_t r = 0; r < 2; r++) {
        const uint8_t *n = b.n[mover ^ r];
        uint8_t row = (uint8_t)(r * SIDE_ROWS);
        for (uint8_t p = 1; p <= 24; p++, row += 4) {
            uint8_t k = n[p];
            if (!k) continue;
            f(row, (uint8_t)1);
            if (k >= 2) f((uint8_t)(row + 1), (uint8_t)1);
            if (k >= 3) f((uint8_t)(row + 2), (uint8_t)1);
            if (k > 3) f((uint8_t)(row + 3), (uint8_t)(k - 3));
        }
        if (n[bg::BAR]) f(row, n[bg::BAR]);
        if (n[bg::OFF]) f((uint8_t)(row + 1), n[bg::OFF]);
    }
}

// How good the position is for `mover`, who has just moved: bigger is
// better. Not a probability yet (comparing plays does not need one).
int32_t eval(const bg::Board &b, uint8_t mover);
void forget();                      // the tables changed (the trainer): start the next eval afresh
// ... as the chance that `mover` wins, 0..65535.
uint16_t chance(int32_t evaluation);

}  // namespace net
