// CHBackgammon - casino backgammon for the RPGame handheld (CH32X035,
// 128x128 ST7735, piezo), in the look of CHBlackjack and CHChess.
//
// The files:
//   Rules.*               the rules: a checker's step, every play a roll allows
//   Net.*, Race.*, Ai.*   the CPU: a small neural network that learned the game
//                         by playing itself (tools/train), a race table, and
//                         the search that asks them
//   Cube.*                the CPU and the doubling cube, in match play
//   Match.*, Notation.*   a match's flow (no graphics); a play as "24/18 13/11"
//   Stage.*, Table.*      the play screen in motion; the board and its pieces
//   Screens.*, Frame.*    title, setup, play, options; the frame loop
//   Font.*, Fx.*          the display font; particles and banners
//   Sounds.*, Save.*      the sound effects; what a save holds
//   config.h              build switches
//   src/ai/*Data.cpp      the network's, the race's and the match equity
//                         tables (generated by tools/train)
//   src/assets/           the art, generated by tools/assets.py
#include <RPGame.h>
#include "config.h"
#include "Frame.h"

void setup() {
    rpgame.boot();
    gfx_begin(GFX_DIV2, GFX_12BPP);
    frame::begin();
    rpgame.setFrameRate(CHBG_FPS);
}

void loop() {
    frame::run();
}
