// Generated by tools/assets.py - do not edit.
// Sprites in the span4 format (the RPGame library's rpgame/Draw.h).
#pragma once
#include <stdint.h>

extern const uint8_t TOKEN_CHERRIES[68];
extern const uint8_t TOKEN_BANANA[56];
extern const uint8_t TOKEN_APPLE[68];
extern const uint8_t TOKEN_STRAWBERRY[70];
extern const uint8_t DIE[62];
extern const uint8_t SNAKE_HEAD[58];
extern const uint8_t SNAKE_HEAD_OPEN[61];
extern const uint8_t CROWN[28];
extern const uint8_t LOGO_SNAKES[448];
constexpr uint8_t LOGO_SNAKES_W = 124, LOGO_SNAKES_H = 28;
extern const uint8_t LOGO_LADDERS[168];
constexpr uint8_t LOGO_LADDERS_W = 89, LOGO_LADDERS_H = 14;
extern const uint8_t HAND[111];
extern const uint8_t *const TOKEN[4];        // by seat
constexpr uint8_t HAND_TIP = 5;          // the fingertip's column (bottom row)
