// Generated by tools/assets.py - do not edit.
#pragma once
#include <stdint.h>

extern const uint8_t HAND[111];                            // span4, fingertip on the bottom row
constexpr uint8_t HAND_TIP = 5;                           // its column
extern const uint8_t ARROW_R[35], ARROW_D[52];   // span4, 9 x 9: the way the word runs
extern const uint8_t FONT[598];                         // the display font (tools/art/font.txt): per glyph its
                                                            // character, width, top << 4 | rows, the rows' bits; 0 ends
extern const uint8_t TILEFONT[546];                     // the tiles' letters (tools/art/tilefont.txt): per glyph
                                                          // width | (rows - 8) << 4, then the rows' bits
