// GENERATED by tools/train/train.py race - do not edit.
// race::cost()'s table, fitted to the exact rolls-to-bear-off of every
// home-board position (see Race.h).
#include "../../Race.h"

namespace race {

RACE_CONST uint8_t TABLE[TABLE_SIZE] = {
    4, 5, 6, 7,     // the 1 point: a first, second and third checker, each one more
    5, 6, 6, 7,     // the 2 point: a first, second and third checker, each one more
    6, 7, 7, 8,     // the 3 point: a first, second and third checker, each one more
    7, 8, 8, 9,     // the 4 point: a first, second and third checker, each one more
    8, 9, 9, 11,     // the 5 point: a first, second and third checker, each one more
    10, 11, 11, 12,     // the 6 point: a first, second and third checker, each one more
    18,                // and to start with
};

}  // namespace race
