// GENERATED by tools/assets.py - do not edit.
// Art drawn for CHSlots, 2026, bateske (tools/art/, tools/assets.py).
#pragma once
#include <stdint.h>

extern const uint8_t SYMBOLS[5514];
extern const uint16_t SYMBOL_AT[33];
constexpr int SYM_SIZE = 22;
constexpr int SYM_FORTUNE = 15;
constexpr int SYM_SWEET = 25;
extern const uint8_t LOGO[135];
constexpr int LOGO_W = 68;
constexpr int LOGO_H = 15;
