// Generated by tools/assets.py - do not edit.
// Sprites in the span4 format (the RPGame library's rpgame/Draw.h); LOGO as 1-bit rows.
#pragma once
#include <stdint.h>

extern const uint8_t TOKEN_CHERRIES[68];
extern const uint8_t TOKEN_BANANA[56];
extern const uint8_t TOKEN_APPLE[68];
extern const uint8_t TOKEN_STRAWBERRY[70];
extern const uint8_t HOUSE[24];
extern const uint8_t HOTEL[40];
extern const uint8_t CARD_DECK[54];
extern const uint8_t CHIPS[56];
extern const uint8_t DIE[62];
extern const uint8_t ICON_GO[44];
extern const uint8_t ICON_CHANCE[19];
extern const uint8_t ICON_CHEST[26];
extern const uint8_t ICON_TAX[24];
extern const uint8_t ICON_RAIL[21];
extern const uint8_t ICON_BULB[20];
extern const uint8_t ICON_WATER[20];
extern const uint8_t ICON_JAIL[66];
extern const uint8_t ICON_PARKING[30];
extern const uint8_t LOGO[182];
constexpr uint8_t LOGO_W = 101, LOGO_H = 14;
extern const uint8_t HAND[111];
extern const uint8_t *const TOKEN[4];        // by seat
constexpr uint8_t HAND_TIP = 5;          // the fingertip's column (bottom row)
