// GENERATED by tools/assets.py - do not edit.
// The dealer derives from Press-Play-On-Tape/Blackjack (Apache-2.0) by
// filmote & vampirics, recoloured 2026 for RPGame by bateske (CHBlackjack);
// the title lettering is new (tools/art/). See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[487];
extern const uint8_t FACE_NORMAL[119];
extern const uint8_t CHIP_TOP[35];
extern const uint8_t CHIP_SIDE[28];
extern const uint8_t CHIP_SMALL_TOP[31];
extern const uint8_t CHIP_SMALL_SIDE[13];
extern const uint8_t FIELD_PRINT[259];
extern const uint8_t PUCK_ON[60];
extern const uint8_t PUCK_OFF[71];
extern const uint8_t LOGO[220];
constexpr int LOGO_W = 74;
constexpr int LOGO_H = 22;
extern const uint16_t FACE_EDITS[138];
extern const uint16_t FACE_EDIT_AT[7];
