// Generated by tools/assets.py - do not edit.
#pragma once
#include <stdint.h>

extern const uint8_t CHECKER[39];                         // span4, 8 x 8, neutral tones
extern const uint8_t CHECKER_REMAP[2][16];                  // ... as White's, as Red's (tools/art/sides.txt)
extern const uint8_t CHECKER_BIG[121];                    // the same checker, 16 x 16: the close-ups
extern const uint8_t DICE[402];                          // span4 faces 1..6, 12 x 12: DICE + DIE_AT[face - 1]
extern const uint16_t DIE_AT[6];
extern const uint8_t DIE_REMAP[2][16], DIE_USED[2][16];     // each side's dice; and once played
extern const uint8_t HAND[111];                            // span4, fingertip on the bottom row
constexpr uint8_t HAND_TIP = 5;                           // its column
extern const uint8_t FONT[718];                         // the display font (tools/art/font.txt): per glyph its
                                                            // character, width, top << 4 | rows, the rows' bits; 0 ends
