// GENERATED by tools/assets.py - do not edit.
// The croupier and the end-screen lettering are Press Play On Tape's
// (Apache-2.0, by filmote & vampirics), as recoloured for CHBlackjack; the
// glove is CHChess's; the rest was drawn for this game. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[487];  // the croupier 48x42, row spans
extern const uint8_t DEALER_ALT_REMAP[16];  // the NIGHT croupier: remap applied to DEALER
extern const uint8_t FACE_NORMAL[119];  // face patch 24x18 at (12,14), row spans
extern const uint16_t FACE_EDITS[138];  // expression edits: (y*24+x)<<4 | colour; ANGRY RAISED BLINK SMILE SURPRISED TALK
extern const uint16_t FACE_EDIT_AT[7];  // start of each expression in FACE_EDITS, plus end
extern const uint8_t HAND[111];  // the glove 13x16, row spans; fingertip on the bottom row
constexpr int HAND_TIP = 5;  // the fingertip's column
extern const uint8_t CAT1[57];  // the cat 18x10, row spans
extern const uint8_t CAT2[57];  // the cat 18x10, row spans
extern const uint8_t X_L[214];  // x_l 27x25, row spans, then the base centre x, y
extern const uint8_t O_L[168];  // o_l 23x21, row spans, then the base centre x, y
extern const uint8_t CHIP0_L[71];  // chip0_l 15x11, row spans, then the base centre x, y
extern const uint8_t CHIP1_L[126];  // chip1_l 21x16, row spans, then the base centre x, y
extern const uint8_t CHIP2_L[149];  // chip2_l 27x19, row spans, then the base centre x, y
extern const uint8_t X_L1[232];  // x_l1 23x31, row spans, then the base centre x, y
extern const uint8_t X_L2[189];  // x_l2 9x33, row spans, then the base centre x, y
extern const uint8_t O_L1[181];  // o_l1 19x22, row spans, then the base centre x, y
extern const uint8_t O_L2[122];  // o_l2 9x22, row spans, then the base centre x, y
extern const uint8_t X_S[115];  // x_s 17x15, row spans, then the base centre x, y
extern const uint8_t O_S[99];  // o_s 15x13, row spans, then the base centre x, y
extern const uint8_t CHIP0_S[46];  // chip0_s 11x8, row spans, then the base centre x, y
extern const uint8_t CHIP1_S[59];  // chip1_s 13x11, row spans, then the base centre x, y
extern const uint8_t CHIP2_S[88];  // chip2_s 17x13, row spans, then the base centre x, y
extern const uint8_t LOGO[180];  // 'TIC TAC TOE' 120x12, MSB-first rows
constexpr int LOGO_W = 120;
constexpr int LOGO_H = 12;
extern const uint8_t ROYALE[242];  // 'Royale' 88x22, MSB-first rows
constexpr int ROYALE_W = 88;
constexpr int ROYALE_H = 22;
extern const uint8_t YOUWON1[240];  // PPOT lettering 119x16, MSB-first rows
constexpr int YOUWON1_W = 119;
extern const uint8_t YOUWON2[224];  // PPOT lettering 107x16, MSB-first rows
constexpr int YOUWON2_W = 107;
extern const uint8_t BROKE1[192];  // PPOT lettering 91x16, MSB-first rows
constexpr int BROKE1_W = 91;
extern const uint8_t BROKE2[160];  // PPOT lettering 73x16, MSB-first rows
constexpr int BROKE2_W = 73;
