// GENERATED by tools/assets.py - do not edit.
// The host is Press Play On Tape's dealer
// (Apache-2.0, by filmote & vampirics), as recoloured for CHBlackjack.
// See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[487];  // the host 48x42, row spans
extern const uint8_t DEALER_ALT_REMAP[16];  // the NIGHT host: remap applied to DEALER
extern const uint8_t FACE_NORMAL[119];  // face patch 24x18 at (12,14), row spans
extern const uint16_t FACE_EDITS[116];  // expression edits: (y*24+x)<<4 | colour; ANGRY RAISED BLINK SMILE SURPRISED TALK
extern const uint16_t FACE_EDIT_AT[7];  // start of each expression in FACE_EDITS, plus end
