// GENERATED by tools/assets.py - do not edit.
// The caller and the broke-screen lettering are Press Play On Tape's
// (Apache-2.0, by filmote & vampirics), as recoloured for CHBlackjack; the
// glove is CHChess's; the rest was drawn for this game. See NOTICE.
#pragma once
#include <stdint.h>

extern const uint8_t DEALER[487];  // the caller 48x42, row spans
extern const uint8_t DEALER_ALT_REMAP[16];  // the NIGHT caller: remap applied to DEALER
extern const uint8_t FACE_NORMAL[119];  // face patch 24x18 at (12,14), row spans
extern const uint16_t FACE_EDITS[138];  // expression edits: (y*24+x)<<4 | colour; ANGRY RAISED BLINK SMILE SURPRISED TALK
extern const uint16_t FACE_EDIT_AT[7];  // start of each expression in FACE_EDITS, plus end
extern const uint8_t HAND[111];  // the glove 13x16, row spans; fingertip on the bottom row
constexpr int HAND_TIP = 5;  // the fingertip's column
extern const uint8_t HAND_R[89];  // the glove pointing right 16x13, row spans
constexpr int HAND_R_TIP = 5;  // the fingertip's row
extern const uint8_t LOGO[144];  // 'Bingo' 61x18, MSB-first rows
constexpr int LOGO_W = 61;
constexpr int LOGO_H = 18;
extern const uint8_t BROKE1[192];  // PPOT lettering 91x16, MSB-first rows
constexpr int BROKE1_W = 91;
extern const uint8_t BROKE2[160];  // PPOT lettering 73x16, MSB-first rows
constexpr int BROKE2_W = 73;
