// Generated by tools/puzzles/build_pack.py - do not edit.
#pragma once
#include <stdint.h>
#include "../../config.h"

constexpr uint8_t HUFF_MAX = 12;                // the longest code
extern const uint8_t HUFF_COUNT[12];           // codes of each length 1..HUFF_MAX
extern const char HUFF_SYM[58];              // the characters in code order (0 = end of text)
#if CHCW_LEAN
extern const uint8_t BUILTIN[2061];         // the built-in pack, cut to its first 3 puzzles
#else
extern const uint8_t BUILTIN[14031];        // the built-in pack (20 puzzles)
#endif
