"""The match equity table: how likely a player is to win a match from a
score, worked out here from a simple model (not copied from anywhere).

    python tools/train/met.py [src/ai/MetData.cpp]

The model: each game is an even game, and a quarter of the games won are
gammons (worth two); backgammons are rare enough to leave out. The cube is
left out of the games before the Crawford game, which makes the table a
little flatter than tables that model it. After the Crawford game the player
behind doubles at once (the leader then wins the match with any win), so
each of those games is worth two to the trailer.

  MET[a][b]  the chance of the player needing a points against one needing
             b, a game about to start (if exactly one needs a single point
             and the Crawford game is not over, that game is the Crawford
             game);
  POST[b]    the chance of the player needing b against one needing a
             single point, after the Crawford game.
"""
import sys
from functools import lru_cache
from pathlib import Path

N = 7               # the longest match the game offers
GAMMONS = 0.22      # of the games won


@lru_cache(None)
def post(b):
    """Trailer needing b against the leader needing 1, after the Crawford game."""
    if b <= 0:
        return 1.0
    if b == 1:
        return 0.5                      # both need one: the cube no longer matters
    g = GAMMONS
    return 0.5 * ((1 - g) * post(b - 2) + g * post(b - 4))


@lru_cache(None)
def crawford(b):
    """The leader (needing 1) in the Crawford game against a trailer needing b."""
    g = GAMMONS
    lose = (1 - g) * (1 - post(b - 1)) + g * (1 - post(b - 2))
    return 0.5 + 0.5 * lose


@lru_cache(None)
def met(a, b):
    if a <= 0:
        return 1.0
    if b <= 0:
        return 0.0
    if a == 1 and b == 1:
        return 0.5
    if a == 1:
        return crawford(b)
    if b == 1:
        return 1 - crawford(a)
    g = GAMMONS
    return (0.5 * ((1 - g) * met(a - 1, b) + g * met(a - 2, b)) +
            0.5 * ((1 - g) * met(a, b - 1) + g * met(a, b - 2)))


def q16(v):
    return min(65535, round(v * 65536))


def main():
    for a in range(1, N + 1):
        print(" ".join(f"{met(a, b):.3f}" for b in range(1, N + 1)), f"  post {post(a):.3f}")
    if len(sys.argv) > 1:
        out = Path(sys.argv[1])
        rows = ",\n".join("    {" + ", ".join(str(q16(met(a, b))) for b in range(1, N + 1)) + "}"
                          for a in range(1, N + 1))
        out.write_text(
            "// GENERATED by tools/train/met.py - do not edit.\n"
            "// The match equity table (see that file for the model it comes from).\n"
            '#include "../../Cube.h"\n\nnamespace cube {\n\n'
            f"const uint16_t MET[{N}][{N}] = {{\n{rows},\n}};\n\n"
            f"const uint16_t POST[{N}] = {{" + ", ".join(str(q16(post(b))) for b in range(1, N + 1)) + "};\n\n"
            "}  // namespace cube\n", newline="\n")
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
