// CHPoker - casino poker for the RPGame handheld (CH32X035, 128x128 ST7735,
// piezo): Texas Hold'em, Five Card Draw, Omaha and Seven Card Stud against
// three CPU players, in the style of CHBlackjack and CHChess.
//
// The files:
//   Screens.*        title, lobby, the table's pause menu, options, stats, endings
//   Table.*          the rules and the flow of a hand (no graphics; host-tested)
//   Cards.h, Hand.*  the cards; the hand evaluator
//   Ai.*             the CPU players (Monte Carlo equity)
//   Variants.*       the four games and the three tables' stakes, as data
//   Stage.*          the table's events turned into motion; drawing the table
//   CardArt.*        cards and chips;  Bar.*: the action bar;  Layout.h: where
//                    everything goes
//   Fx.*, Sounds.*   particles, banners, floating texts; the sound effects
//   Save.*           what a save holds
//   src/assets/      the art, generated by tools/assets.py
//
// Frame loop: logic runs at a fixed 60 Hz while the previous frame is still
// going out over DMA; drawing waits for it (one framebuffer), then the new
// frame is sent. A CPU player's thinking runs on the first logic tick of a
// frame only, a fixed amount each time, so it never snowballs into the
// catch-up ticks and lockstep runs stay deterministic.
#include <RPGame.h>
#include "config.h"
#include "Screens.h"
#include "Sounds.h"

void setup() {
    rpgame.boot();
    dbg::begin("CHPK " CHPK_VERSION);     // the debug protocol's hello (CHGAME_DEBUG builds)
    gfx_begin(GFX_DIV2, GFX_12BPP);
    pal::init();
    screens::begin();
    rpgame.setFrameRate(CHPK_FPS);
}

void loop() {
    dbg::poll();
    if (!rpgame.nextFrame()) return;
    dbg::markUpdateStart();
    uint8_t ticks = 0;
    do {
        rpgame.pollButtons();
        pal::tick();
        audio::update();
        screens::update(ticks == 0);
    } while (++ticks < 3 && rpgame.nextFrame());
    gfx_wait();
    pal::commit();
    dbg::markRenderStart();
    screens::render(rpgame.frameCount);
    dbg::markRenderEnd();
    gfx_flushAsync();
}
